kind: Deployment
apiVersion: apps/v1
metadata:
# set your lab user name
  name:  {{ .Release.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
# set your lab user name
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
# set your lab user name
        app: {{ .Release.Name }}
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          # name: hello-world
          name: {{ .Release.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          imagePullPolicy: IfNotPresent
# update with the image you build in part 1
          # image: 'quay.io/jonatang/app-dev-lab:v1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10